# Default values

replicaCount: 3
storage: 20Gi

image:
  repo: ghost

pod:
  port: 2368

nameOverride: ""
fullnameOverride: ""

service:
  enabled: false
  tier: frontend
  type: LoadBalancer
  port: 2368
